### ISSUE TITLE
% causes an error

### ISSUE THREAD

**Issue by Evil-4** [AdvancedPlugins/Chat#178]
### Describe the bug

typing % in chat causes an error

[17:43:52 ERROR]: Could not pass event AsyncPlayerChatEvent to AdvancedChat v1.3.9
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at net.advancedplugins.chat.impl.commons.effects.actions.ActionExecutionBuilder.lambda$processVariables$1(ActionExecutionBuilder.java:197) ~[AdvancedChat-1.3.9.jar:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.advancedplugins.chat.impl.commons.effects.actions.ActionExecutionBuilder.processVariables(ActionExecutionBuilder.java:197) ~[AdvancedChat-1.3.9.jar:?]
        at net.advancedplugins.chat.abilities.custom.OnMessageTrigger.activate(OnMessageTrigger.java:28) ~[AdvancedChat-1.3.9.jar:?]
        at net.advancedplugins.chat.listeners.ChatListener.onChat(ChatListener.java:49) ~[AdvancedChat-1.3.9.jar:?]
        at net.advancedplugins.chat.Core.lambda$registerChatListener$2(Core.java:454) ~[AdvancedChat-1.3.9.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2318) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2167) ~[?:?]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[paper-1.20.4.jar:git-Paper-497]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

It's just that when I write % in the chat, an error pops up

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting!

**Comment by Schroddinger** [comment]
(Sorry for not creating a new issue, but I thinks this might be related)
Hi, typing the sharp `#` is triggering a similar error:

```
[05:00:37 INFO]: []  Biquaternions ➦ #
[05:00:38 WARN]: [AdvancedChat] Plugin AdvancedChat v1.4.6 generated an exception while executing task 7396463
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at AdvancedChat-1.4.6.jar/net.advancedplugins.chat.ai.AIHandler.processRequest(AIHandler.java:77) ~[AdvancedChat-1.4.6.jar:?]
        at AdvancedChat-1.4.6.jar/net.advancedplugins.chat.ai.AIHandler.lambda$init$0(AIHandler.java:52) ~[AdvancedChat-1.4.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
        ... 12 more
```

**Comment by ThomasWega** [comment]
Please create a new issue and I will handle it  asap
