### ISSUE TITLE
Exception when sending # in the chat

### ISSUE THREAD

**Issue by Schroddinger** [AdvancedPlugins/Chat#199]
### Describe the bug

Sending `#` throws this exception:

```
[05:00:37 INFO]: []  Biquaternions ➦ #
[05:00:38 WARN]: [AdvancedChat] Plugin AdvancedChat v1.4.6 generated an exception while executing task 7396463
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at AdvancedChat-1.4.6.jar/net.advancedplugins.chat.ai.AIHandler.processRequest(AIHandler.java:77) ~[AdvancedChat-1.4.6.jar:?]
        at AdvancedChat-1.4.6.jar/net.advancedplugins.chat.ai.AIHandler.lambda$init$0(AIHandler.java:52) ~[AdvancedChat-1.4.6.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
        ... 12 more
```

### How to reproduce

Send a message containing `#` in the chat.
This happened inside a channel (public channel).

**Comment by ThomasWega** [comment]
Can you send your whole config please?

**Comment by ThomasWega** [comment]
also your plugin list please

**Comment by Schroddinger** [comment]
Let me know when you read this please, so I can delete these files.

```
[15:05:58 INFO]: Paper Plugins: (1):
[15:05:58 INFO]:  - LottusLifesteal
[15:05:58 INFO]: Bukkit Plugins: (35):
[15:05:58 INFO]:  - AdvancedChat, BetterChatBubbles, DriveBackupV2, fairy-lib-plugin, InvSeePlusPlus, Iris, Lands, LibsDisguises, LifestealCore, LiteBans
[15:05:58 INFO]:  LPX, LuckPerms, ModelEngine, MythicCrucible, MythicDungeons, MythicMobs, OpenAudioMc, packetevents, PlaceholderAPI, PremiumVanish
[15:05:58 INFO]:  ProtocolLib, PvPManager, raytraced-antixray, raytraced-entity-culling, raytraced-tile-culling, RoyaleEconomy, SimpleTpa, TAB, UltimateAutoRestart, Vault
[15:05:58 INFO]:  ViaBackwards, ViaVersion, VillagerOverhaul, Vulcan, WorldEdit
```

Just for context, in case is necessary:
LottusLifesteal is a core custom made plugin for the server to add some new mechanics and create bridges between plugins that have no built-in compatibility. The only chat-related feature from this plugin is to send the messages from AdvancedChat to BetterChatBubbles, so messages from the public channel display as a chat bubble on top of the player's head.

[AdvancedChat.zip](https://github.com/user-attachments/files/17116656/AdvancedChat.zip)

**Comment by GC-spigot** [comment]
Solved!
