### ISSUE TITLE
Error fetching player skin

### ISSUE THREAD

**Issue by xWindsweptx** [AdvancedPlugins/Chat#206]
### Describe the bug

This error spams the console anytime someone logs into the servers. 

[12:07:24 ERROR]: [AdvancedChat] Error fetching player skin.
javax.imageio.IIOException: Can't get input stream from URL!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407) ~[?:?]
	at AdvancedChat-1.5.2.jar/net.advancedplugins.chat.chat.player_head.ChatHead.lambda$fetchHeadLines$1(ChatHead.java:99) ~[AdvancedChat-1.5.2.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.FileNotFoundException: https://minotar.net/avatar/.Windswept7925/8.png
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1994) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?]
	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?]
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405) ~[?:?]

### How to reproduce

A player just has to log into the server. It seems to do it more when its a bedrock player.

### Server Log

https://mcpaste.io/8fa115040e864ddc

**Comment by ThomasWega** [comment]
If a bedrock player joins, does it add a dot before his name? Because the name of the player is `.Windswept7925`, so that causes the issue

**Comment by xWindsweptx** [comment]
Yes, it does that for every bedrock player.

**Comment by ThomasWega** [comment]
Should be fixed in the next update
