### ISSUE TITLE
AdvancedChat Console Errors

### ISSUE THREAD

**Issue by xWindsweptx** [AdvancedPlugins/Chat#219]
### Describe the bug

**This warning spams the consoles even after we updated to the newest jar file.** 

15.11 07:38:22 [Server] WARN [AdvancedChat] Task #9901 for AdvancedChat v1.6.1 generated an exception
15.11 07:38:22 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.advancedplugins.chat.chat.player_head.ChatHead.fetchHeadLines()" because the return value of "net.advancedplugins.chat.chat.player_head.ChatHead.of(int, String)" is null
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.chat.player_head.ChatHead.getIfCached(ChatHead.java:80) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.chat.player_head.ChatHead.getBlocking(ChatHead.java:60) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.parsePlaceholdersWithoutPAPI(TextNew.java:98) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.renderWithPAPI(TextNew.java:206) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.getParsedMessage(TextNew.java:320) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.sendToastMessageCommon(TextNew.java:282) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:250) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:332) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at AdvancedChat-1.6.1 (1).jar/net.advancedplugins.chat.motd.ChatMOTDListener.lambda$onPlayerJoin$0(ChatMOTDListener.java:29) ~[AdvancedChat-1.6.1 (1).jar:?]
15.11 07:38:22 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:22 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:22 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2301-a43711d]
15.11 07:38:26 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

Happens randomly throughout all of our servers. Usually at start up or when a player logs in. Sometimes it will kick the player.

### Server Log

https://mcpaste.io/7afa56b6f9e8716a

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Really weird issue tbh
