### ISSUE TITLE
advancedchat still not loaded

### ISSUE THREAD

**Issue by codnRR** [AdvancedPlugins/Chat#223]
### Describe the bug

i use 1.17.1 paper and advancedchat plugin, looking like adapt for 1.17 on advancedplugins.net so im buying and there is my logs

[07:18:11] [Server thread/INFO]: [AdvancedChat] Enabling AdvancedChat v1.6.8
[07:18:11] [Server thread/ERROR]: Error occurred while enabling AdvancedChat v1.6.8 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class net.kyori.adventure.text.minimessage.tag.standard.StandardTags
	at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$BuilderImpl.<init>(MiniMessageImpl.java:174) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessage.builder(MiniMessage.java:303) ~[?:?]
	at net.advancedplugins.chat.utils.TextNew.<clinit>(TextNew.java:391) ~[?:?]
	at net.advancedplugins.chat.Core.startupTasks(Core.java:173) ~[?:?]
	at net.advancedplugins.chat.Core.startup(Core.java:135) ~[?:?]
	at net.advancedplugins.chat.impl.utils.plugin.AdvancedPlugin.onEnable(AdvancedPlugin.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)' [in thread "Server thread"]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[?:?]
	at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:58) ~[?:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:58) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:55) ~[?:?]
	at org.mineacademy.winter.lib.model.SimpleComponent.fromMini(SimpleComponent.java:749) ~[?:?]
	at org.mineacademy.winter.lib.settings.SimpleSettings.<clinit>(SimpleSettings.java:63) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.mineacademy.winter.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:59) ~[?:?]
	at org.mineacademy.winter.lib.platform.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:226) ~[?:?]
	at org.mineacademy.winter.lib.platform.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:93) ~[?:?]
	at org.mineacademy.winter.lib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:365) ~[?:?]
	... 10 more
[07:18:11] [Server thread/INFO]: [AdvancedChat] Disabling AdvancedChat v1.6.8

### How to reproduce

none

### Screenshots / Videos

none

### Server Log

https://mcpaste.io/05197248d0e255e0

**Comment by ThomasWega** [comment]
It seems to be caused by the Winter plugin. Try removing it

**Comment by codnRR** [comment]
https://mcpaste.io/551304c37953e2ab

It has nothing to do with Winter, I deleted it and reinstalled it and here is the result.

**Comment by codnRR** [comment]
https://mcpaste.io/c24797c6d0c33a24

It has nothing to do with Winter, I deleted it and reinstalled it and here is the result.

**Comment by ThomasWega** [comment]
Reinstalled it? I wanted you to try without it

**Comment by codnRR** [comment]
If you are not going to examine it, why do you want the log? I am saying that I tried it without installing it. I meant that I reinstalled advancedchat without winter.

**Comment by ThomasWega** [comment]
Will be fixed in the next update. Thanks for reporting

**Comment by codnRR** [comment]
https://mcpaste.io/f2825db9784b81e4

I just installed it 1 plugins to see if there were any errors in anything else, but even the commands alone don't work, it keeps giving errors, tested it in its current version, 1.6.9.
