### ISSUE TITLE
advancedchat still dont work 1.17.1

### ISSUE THREAD

**Issue by codnRR** [AdvancedPlugins/Chat#224]
### Describe the bug

I just installed it 1 plugins to see if there were any errors in anything else, but even the commands alone don't work, it keeps giving errors, tested it in its current version, 1.6.9.

### How to reproduce

.

### Server Log

https://mcpaste.io/f2825db9784b81e4

**Comment by SirJben** [comment]
```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.11+9) Host: Linux 5.15.0-107-generic (amd64)
Loading libraries, please wait...
[14:21:25 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:21:25 INFO]: Reloading ResourceManager: Default, bukkit
[14:21:26 INFO]: Loaded 7 recipes
[14:21:27 INFO]: Starting minecraft server version 1.17.1
[14:21:27 INFO]: Loading properties
[14:21:27 INFO]: This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
[14:21:27 INFO]: Server Ping Player Sample Count: 12
[14:21:27 INFO]: Using 4 threads for Netty based IO
[14:21:28 INFO]: Default game type: SURVIVAL
[14:21:28 INFO]: Generating keypair
[14:21:28 INFO]: Starting Minecraft server on 0.0.0.0:59333
[14:21:28 INFO]: Using epoll channel type
[14:21:28 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[14:21:28 INFO]: Paper: Using Java cipher from Velocity.
[14:21:28 INFO]: [AdvancedChat] Loading 1 libraries... please wait
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
[14:21:28 INFO]: [AdvancedChat] Loaded library /home/container/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[14:21:28 INFO]: [AdvancedChat] Loading AdvancedChat v1.6.9
[14:21:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:21:28 INFO]: Preparing level "world"
[14:21:29 INFO]: Preparing start region for dimension minecraft:overworld
[14:21:29 INFO]: Preparing spawn area: 0%
[14:21:29 INFO]: Preparing spawn area: 0%
[14:21:30 INFO]: Preparing spawn area: 0%
[14:21:30 INFO]: Time elapsed: 1198 ms
[14:21:30 INFO]: Preparing start region for dimension minecraft:the_nether
[14:21:30 INFO]: Preparing spawn area: 0%
[14:21:30 INFO]: Preparing spawn area: 0%
[14:21:31 INFO]: Time elapsed: 926 ms
[14:21:31 INFO]: Preparing start region for dimension minecraft:the_end
[14:21:31 INFO]: Preparing spawn area: 0%
[14:21:31 INFO]: Time elapsed: 312 ms
[14:21:31 INFO]: [AdvancedChat] Enabling AdvancedChat v1.6.9
[14:21:32 INFO]: [AdvancedChat] Loaded 18 chat colors
[14:21:32 INFO]: [AdvancedChat] Loaded 33 tags
[14:21:32 INFO]: [AdvancedChat] Loading chat rules...
[14:21:32 INFO]: [AdvancedChat] Registered similarity chat rule
[14:21:32 INFO]: [AdvancedChat] Registered caps chat rule
[14:21:32 INFO]: [AdvancedChat] Registered spam chat rule
[14:21:32 INFO]: [AdvancedChat] Registered emojis chat rule
[14:21:32 INFO]: [AdvancedChat] Registered advertising chat rule
[14:21:32 INFO]: [AdvancedChat] Loaded 5 chat rules
[14:21:32 INFO]: [AdvancedChat] Loaded 5 chat games
[14:21:32 INFO]: [AdvancedChat] Loaded 2 join message formats
[14:21:32 INFO]: [AdvancedChat] Loaded 2 announcements
[14:21:32 INFO]: [AdvancedChat] ProtocolLib is not enabled, Customizer will not work.
[14:21:32 INFO]: [AdvancedChat] Registered mod chat format
[14:21:32 INFO]: [AdvancedChat] Registered donator chat format
[14:21:32 INFO]: [AdvancedChat] Registered owner chat format
[14:21:32 INFO]: [AdvancedChat] Registered default chat format
[14:21:32 INFO]: Running delayed init tasks
[14:21:33 INFO]: [AdvancedChat] Loaded 2814 swear words.
[14:21:33 INFO]: Done (5.806s)! For help, type "help"
MintServers Server marked as running...
[14:21:33 INFO]: Timings Reset
[14:22:49 INFO]: UUID of player SirJben is d68fe713-3be4-4183-a016-826cf81f7148
[14:22:49 INFO]: SirJben[/143.44.145.154:7320] logged in with entity id 124 at ([world]-5.5, 68.0, -1.5)
[14:22:50 WARN]: [AdvancedChat] Task #14 for AdvancedChat v1.6.9 generated an exception
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:58) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:58) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:55) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.MiniMessageConverter.getFromLegacy(MiniMessageConverter.java:48) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.render(TextNew.java:70) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.renderWithPAPI(TextNew.java:212) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.getParsedMessage(TextNew.java:320) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessageCommon(TextNew.java:282) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:250) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:332) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.motd.ChatMOTDListener.lambda$onPlayerJoin$0(ChatMOTDListener.java:29) ~[AdvancedChat-1.6.9.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:23:03 ERROR]: Could not pass event AsyncPlayerChatEvent to AdvancedChat v1.6.9
java.lang.NoClassDefFoundError: Could not initialize class net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances
        at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:55) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.MiniMessageConverter.getFromLegacy(MiniMessageConverter.java:48) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.render(TextNew.java:70) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.stripColor(TextNew.java:61) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.listeners.ChatListener.onChat(ChatListener.java:55) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.Core.lambda$registerChatListener$2(Core.java:465) ~[AdvancedChat-1.6.9.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[patched_1.17.1.jar:git-Paper-411]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[patched_1.17.1.jar:git-Paper-411]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2179) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2090) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2056) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[app:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)' [in thread "Server thread"]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:58) ~[AdvancedChat-1.6.9.jar:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:58) ~[AdvancedChat-1.6.9.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:55) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.MiniMessageConverter.getFromLegacy(MiniMessageConverter.java:48) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.render(TextNew.java:70) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.renderWithPAPI(TextNew.java:212) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.getParsedMessage(TextNew.java:320) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessageCommon(TextNew.java:282) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:250) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.utils.TextNew.sendToastMessage(TextNew.java:332) ~[AdvancedChat-1.6.9.jar:?]
        at net.advancedplugins.chat.motd.ChatMOTDListener.lambda$onPlayerJoin$0(ChatMOTDListener.java:29) ~[AdvancedChat-1.6.9.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        ... 1 more
[14:23:03 INFO]: <SirJben> Test

```

**Comment by ThomasWega** [comment]
The adventure api we use is just too old on 1.17. We will most likely be removing support for 1.17 and moving it to 1.18+. Apologies, but there is nothing we can really do
